Feature/ct 2
JuliaTsaruk/internship pull request #2
Opened 2021-04-07 22:11 UTC by JuliaTsaruk

2021-04-08 07:39 UTC, DenisKalyanov requested changes

2021-04-08 07:39 UTC, DenisKalyanov commented on index.html
> +                <div class="header_number">
Эта обёртка не нужна, тег `<a>` может прожить из без оборачивания в `<div>`

2021-04-08 07:39 UTC, DenisKalyanov commented on reset/reset.css
> +video {
По-моему, чтобы не прописывать все теги, вместо них нужно указать * 
Тут ведь указано много тегов которые мы даже не планируем использовать.

2021-04-08 07:39 UTC, DenisKalyanov commented on styles/style.css
> +    height: 40.63rem;
Лучше height не фиксировать. Если содержимое блока будет нуждаться в большей высоте, то оно выпадет.
Если мы хотим задать высоту, то тогда используем min-height, в таком случае, при необходимости высота будет увеличиваться.

2021-04-08 07:39 UTC, DenisKalyanov commented on styles/style.css
> +    text-transform: uppercase;
Зачем? Если можно сразу написать заглавными буквами.

2021-04-08 07:39 UTC, DenisKalyanov commented on index.html
> +                    <div class="first-section_info">
first-section_info -этот класс нигде не используется. Зачем он?

2021-04-08 07:39 UTC, DenisKalyanov commented on styles/style.css
> +    bottom: 14.2rem;
Мне кажется, что relative у этого `div` совсем не `button`, а отталкивается он от края `body`

2021-04-08 07:39 UTC, DenisKalyanov commented on styles/style.css
> +    position: absolute;
От чего он отталкивается? блок first-round не его родитель.

2021-04-08 07:39 UTC, DenisKalyanov commented on index.html
> +                        <img class="phone_image" src="/images/phone-img.png">
Если блок в фигме image находиться внутри двух блоков(синих кругов) то почему тут first-round, second-round и img это три обособленных элемента?
Возможно целесообразно будет сократить количество блоков и в `<div class="first-round"></div>` просто вложить тег `а`, а саму иконку добавить с помощью before или after.

2021-04-08 07:39 UTC, DenisKalyanov commented on README.md
> +***MOVEE website***<br>
тут не нужно `<br>`

2021-04-08 07:39 UTC, DenisKalyanov commented on index.html
> +                    <a href="#">8(029)-999-12-13</a>
Добавь возможность набора номера при клике на него. (нажали -> пошёл вызов)

2021-04-08 07:39 UTC, DenisKalyanov commented on styles/style.css
> +    width: 120rem;
А если разрешение монитора у человека будет больше чем 120rem, остальное пространство будет белым?

2021-04-08 07:39 UTC, DenisKalyanov commented on index.html
> +                        <p class="first-section_article2">По Москве и области</p>
Вышла опечатка в Figme)) 
Можно удалить этот блок "По Москве и области" у нас будет только Брест, в фигме поправил.

2021-04-08 07:39 UTC, DenisKalyanov commented on index.html
> +                        <img class="package-img" src="/images/package-img.png" alt="image">
package-img зачем каждому img отдельный класс, если стилизуются они одинаково.

2021-04-08 07:39 UTC, DenisKalyanov commented on index.html
> +                    <img class="car_image" src="/images/first-section_car.png" alt="img">
Может не стоит вставлять man и  car через теги, а сделать их как background и выровнять с помощью backgroun-position? 
Это позволит сократить HTML код и они не будут нам мешать при позиционировании других блоков. 
Изменять это или нет решать тебе.

2021-04-08 07:39 UTC, DenisKalyanov commented on reset/reset.css
> +  display: block;
Зачем эта команда, если эти теги и так все строчные.

2021-04-08 07:39 UTC, DenisKalyanov commented on styles/style.css
> +    position: relative;
Зачем этот блок position: relative и index 2 ?

2021-04-08 07:39 UTC, DenisKalyanov commented on styles/style.css
> +    position: relative;
Зачем этот блок relative?
что мы будем позиционировать относительно его?

Луче чаще использовать display: flex и позиционировать элементы с помощью его, я скидывал ссылку на шпаргалку по флексам. 
Флексы это крутая штука :)

2021-04-08 07:39 UTC, DenisKalyanov commented on styles/style.css
> +        text-transform: uppercase;
Лучше сразу написать текст большими буквами. Вдруг стили не подгрузятся или ещё чего...

2021-04-08 07:39 UTC, DenisKalyanov commented on styles/style.css
> +        font-weight: 700;
Не стоит это дважды дублировать, стили сохраняются, нужно указать для мобилки только то что изменим.

2021-04-08 07:39 UTC, DenisKalyanov commented on styles/style.css
> +        display: none;
как насчёт того, чтобы написать:
.button_second-border,
.first-round,
.second-round,
.phone_image,
.car_image {
        display: none;
    }

2021-04-08 07:39 UTC, DenisKalyanov commented on styles/style.css
> +        left: -16.5rem;
Что б выровнять абсолютный элемент по центру родителя:
top:50%;
left:50%;
transform:translate(-50%, -50%);

2021-04-08 10:04 UTC, JuliaTsaruk commented on styles/style.css
> +    text-transform: uppercase;
На курсах говорили, что необходимо писать только так. А заглавными буквами в html писать устаревшее и так никто уже не пишет. Да и легче удалить/добавить одну строчку в css, чем набирать новый текст в html при необходимости поменять строчные на заглавные и наоборот.

2021-04-08 10:10 UTC, JuliaTsaruk commented on index.html
> +                    <div class="first-section_info">
Просто я создаю сначала структуру в html и сразу прописываю классы основным тегам, а уже потом перехожу в css.

2021-04-08 10:14 UTC, JuliaTsaruk commented on styles/style.css
> +    position: relative;
Я люблю флексы) Но здесь я просто не смогла расположить картинки при помощи флексов как в макете и в ход уже пошло всё.

2021-04-08 10:17 UTC, DenisKalyanov commented on styles/style.css
> +    text-transform: uppercase;
Логика в твоих словах есть, но у нас в данном случае MOVEE используется как логотип, поэтому текст меняться тут не будет и условие не обязательное. 
Другой случай если данные приходят с бэкэнд, мы не знаем какие они, а отобразить нужно в верхнем/нижнем регистре, тогда да, использование этого свойства целесообразно.  
Это не принципиальное замечание, просто в данном случае это совсем не имеет значения. Написать заглавными или добавлять лишнюю строку кода в css.

2021-04-08 11:34 UTC, JuliaTsaruk commented on styles/style.css
> +    height: 40.63rem;
Если не фиксировать height, то длина моей секции больше, чем необходимо по макету и это пока единственный способ, которым я смогла подогнать длину к длине макета.

2021-04-08 12:33 UTC, DenisKalyanov commented on styles/style.css
> +    height: 40.63rem;
height - высота. 
Попробуй посмотреть через F12, что заставляет твою высоту быть больше чем нужно. Возможно внутри есть какой-то блок, который так и наровит занять всё свободное пространство, вот его и нужно уменьшать.

2021-04-09 13:41 UTC, DenisKalyanov approved these changes

2021-04-09 16:08 UTC, merged