Feature/ct 3
JuliaTsaruk/internship pull request #3
Opened 2021-04-13 12:29 UTC by JuliaTsaruk

2021-04-13 14:25 UTC, DenisKalyanov requested changes

2021-04-13 14:25 UTC, DenisKalyanov commented on index.html
> +            <ol>
В официальной документации пишет, что списки больше подходят для хранения в них каких-то строковых значений. А тут мы уже напихали огого. Решение интересное, но лучше цифры тоже обернуть в тег и стилизовать отдельно.

2021-04-13 14:25 UTC, DenisKalyanov commented on index.html
> +                        <span class="list__title list__title-desk font"> Погрузка и транспортировка вещей</span>
А по БЭМ  у нас не должен быть верхний блок list, а в нём уже блок__элемент

2021-04-13 14:25 UTC, DenisKalyanov commented on index.html
> +        <div class="how-it-works__list">
Наверно тут этот `див` не нужен, стилизуй сразу `ol`

2021-04-13 14:25 UTC, DenisKalyanov commented on index.html
> +            <div class="slider__direction">
Точно ли не обойтись без этого дива?

2021-04-13 14:25 UTC, DenisKalyanov commented on index.html
> +            <img class="slider__choice-mob" src="/images/slider-dots.png" alt="image">
Почему все кнопки сделаны одной картинкой? Как мы будем придавать им интерактивности?
Тут должно быть ну наверно 5 картинок, и при hover/active она должна заменяться.

Или это 5 span округлённых и залитых черным цветом. А при ховере у них появляется желтый бордер. Вот это вообще самая рациональная и менее затратная операция по памяти.

2021-04-13 14:25 UTC, DenisKalyanov commented on index.html
> +            <div class="slider__direction">
Нужна ли эта обёртка?

2021-04-13 14:25 UTC, DenisKalyanov commented on styles/style.css
> +    background: #FED100;
background-color и никак иначе! 
Если при работе с обычным css прокатывает. то при работе с фреймворками будет выдавать ошибку.

2021-04-13 14:25 UTC, DenisKalyanov commented on styles/style.css
> +    .how-it-works__list ol li{
Ну если уже используется БЭМ, то наверно нужно присваивать классы и `ol`, `li` и стилизовать сразу li
БЭМ ведь предусматривает переиспользование стилей, мы же не будем переиспользовать их как:
`.how-it-works__list ol li`

2021-04-13 14:25 UTC, DenisKalyanov commented on styles/style.css
> +        border-bottom: #FED100;
а толщина, стиль?

2021-04-13 14:25 UTC, DenisKalyanov commented on styles/style.css
> +    background: #FFFFFF;
background-color

2021-04-13 14:25 UTC, DenisKalyanov commented on index.html
> +                <h3 class="clients__name small-heading">Ирина</h3>
Вряд ли Ирина это прямо заголовок.

2021-04-13 14:25 UTC, DenisKalyanov commented on index.html
> +                <h3 class="clients__name small-heading">Светлана Васильевна </h3>
Светлана Васильевна, так звали мою школьную учительницу по математике, но в данном контексте не стоит оборачивать её в тег h3, это не заголовок.

2021-04-13 14:25 UTC, DenisKalyanov commented on index.html
> +                <p>1 фургон</p>
Почему выше по коду 
`<span class="list__title font">Распаковка и расстановка мебели</span>` это span,
a `1 фургон` обёрнут в `p`.

```
<p>1 газель - 3 метра </p>
<p>2 грузчика</p>
<p>Переезд за 4 часа</p>
```
Может заменим эти 3 тега, на 1 p + br

```
<p>1 газель - 3 метра </br>
2 грузчика</br>
Переезд за 4 часа</p>
```
А можно даже так:
```
<pre>1 газель - 3 метра
2 грузчика
Переезд за 4 часа</pre>

```

2021-04-13 14:25 UTC, DenisKalyanov commented on index.html
> +                <h3 class="clients__name small-heading">Ольга Петрова</h3>
Ольга Петрова ещё жива, не стоит её вписывать в зголовки))

2021-04-13 14:25 UTC, DenisKalyanov commented on styles/style.css
> +    background: #FED100;
background-color plz))

2021-04-13 14:25 UTC, DenisKalyanov commented on styles/style.css
> +    width: 250px;
Так, ну если уже везде rem, то и тут)

2021-04-15 17:48 UTC, DenisKalyanov requested changes

2021-04-15 17:48 UTC, DenisKalyanov commented on styles/style.css
> +.slider__order-button{
Не нашёл hover  для этой кнопки.

2021-04-15 17:48 UTC, DenisKalyanov commented on styles/style.css
> +/*car-park section*/
Комментарии у нас не должны быть. Если только они не поясняют функционал твоего приложения.

2021-04-15 17:51 UTC, DenisKalyanov requested changes

2021-04-15 17:51 UTC, DenisKalyanov commented on styles/style.css
>      margin: 25rem 0 0 38rem;
ОУУ, это ужас))
Тут явно нужно выбить кнопку из потока и отпозиционировать её через top, left, right....

2021-04-19 09:22 UTC, JuliaTsaruk commented on styles/style.css
> +/*car-park section*/
Хорошо. Но если можно, я удалю их в конце разработки. Сейчас они мне облегчают навигацию в CSS файле.

2021-04-19 10:36 UTC, DenisKalyanov requested changes

2021-04-19 10:36 UTC, DenisKalyanov commented on index.html
> +                <ul class="cards__details">
Не нашёл закрывающий тег ul

2021-04-19 11:35 UTC, merged