Feature/ct 4
JuliaTsaruk/internship pull request #4
Opened 2021-04-21 20:21 UTC by JuliaTsaruk

2021-04-22 13:58 UTC, DenisKalyanov requested changes

2021-04-22 13:58 UTC, DenisKalyanov commented on index.html
> +                    <input class="payment-methods__radio-btn" id="cash" name="payment" type="radio" value="cash">
Давай на данном этапе будем избегать id, просто заключи `input` в `label`
id мы возможно ещё воспользуемся при работе с JS
Так же попробуй везде.

2021-04-22 13:58 UTC, DenisKalyanov commented on index.html
> +                        <option value="1">Минская</option>
--> отступ

2021-04-22 13:58 UTC, DenisKalyanov commented on index.html
> +            <ul class="movee-info__list">
Точно ли это нужно делать списком?
Ведь это всё можно сократить до 4х строчек кода.

2021-04-22 13:58 UTC, DenisKalyanov commented on index.html
> +            <ul class="movee-mobile__list">
Также по поводу замены списка на div.

2021-04-22 13:58 UTC, DenisKalyanov commented on index.html
> +                    <li class="navigation__menu-list">Главная</li>
Ну а это же вроде как ссылки.

2021-04-22 13:58 UTC, DenisKalyanov commented on index.html
> +                <p class="call__number font"><a class="call__number-link" href="tel:8(029)-999-12-13">8(029)-999-12-13</a></p>
Эмм, немного не понимаю зачем тут `p`?

2021-04-22 13:58 UTC, DenisKalyanov commented on index.html
> +                        <img src="/images/youtube-small.png" alt="img">
Можно сократить код и сделать img через before/after, но это по твоему желанию. Не критично.

2021-04-22 13:58 UTC, DenisKalyanov commented on styles/style.css
> +.call__button{
у этой кнопки тоже должен быть hover, просто на макете не показан. Но все одинаковые кнопки имеют одинаковые hover

2021-04-23 07:07 UTC, DenisKalyanov requested changes

2021-04-23 07:07 UTC, DenisKalyanov commented on README.md
> +***From 1 to 8 sections***
Мне нужно когда-то это будет сказать)
В этом файлике мы пишем краткое описание проекта. 
Сейчас он не информаттивен.

Мы можем указать что это за проект, как он запускается, кто автор, где можно зайти посмотреть этот проект и прочая информация.

Можно глянуть в интернете проекты или почитать, что тут должно быть. 
Оформить красиво и будет душа радоваться =)

2021-04-23 07:07 UTC, DenisKalyanov commented on index.html
> +                        <span>Наличными курьеру</span>
Можно просто написать без  `<span>`,
`<label><input>Наличными курьеру</label>`

2021-04-23 07:07 UTC, DenisKalyanov commented on index.html
> +                            <label for="confirm">Даю согласие на обработку данных</label>
```
<label>
      <input class="confirmation__checkbox" name="data-processing" type="checkbox" value="confirm">
      Даю согласие на обработку данных
 </label>
```

2021-04-23 09:56 UTC, JuliaTsaruk commented on index.html
> +                        <span>Наличными курьеру</span>
У меня не получилось таким способом добавить псевдоклассы. В интернете нашла примеры только с использованием span.

2021-04-23 17:41 UTC, DenisKalyanov approved these changes

2021-04-26 10:12 UTC, merged