feature/CT-5: was added  JS
JuliaTsaruk/internship pull request #5
Opened 2021-04-29 17:44 UTC by JuliaTsaruk

2021-04-30 08:03 UTC, DenisKalyanov requested changes

2021-04-30 08:03 UTC, DenisKalyanov commented on index.html
> +                <div class="types__cars font active" id="slider-btn" onclick="currentSlide(2)">Каблуки</div>
1. нам не обязательно здесь прописывать обработчик.
Мы можем получить доступ к элементу в файле со скриптом.
```
sliderBtn = document.getElementById(slider-btn);
sliderBtn.onclick = function() {
    alert('Привет'); // при нажатии на твою кнопку нам выскочит "Привет"
  };
```

2. id является уникальным для элемента на всей странице. У тебя 3 одинаковых.

2021-04-30 08:03 UTC, DenisKalyanov commented on scripts/script.js
> +let showList = document.querySelector('.additional-services__more');
Используй по большей части везде const 
Мы ведь не собираемся перезаписывать эту переменную

2021-04-30 08:03 UTC, DenisKalyanov commented on scripts/script.js
> +showList.addEventListener("click" , rotateArrow);
Давай объеденим это в одну функцию. Которая будет срабатывать по нажатию и в зависимости от флага, она будет выполнять определённый код.

Чтобы функция всегда вызывалась одна, а внутри неё она сама понимала, какой класс применить.
Кстати.

2021-04-30 08:03 UTC, DenisKalyanov commented on scripts/script.js
> +var deadline = new Date(Date.parse(new Date()) +  6 * 60 * 60 * 1000);
воу воу.
Откуда у нас в коде взялись var?

Ты вернула мой 2007 )))

2021-04-30 08:03 UTC, DenisKalyanov commented on scripts/script.js
> +let formConfirmation = document.getElementById("form");
Зачем эта переменная если мы её не используем?

2021-04-30 08:03 UTC, DenisKalyanov commented on scripts/script.js
> +        userName.style.border = "0.125rem solid red";
а если там будет пустая строка с пробелами? Как оно отрабатывает?

2021-04-30 08:03 UTC, DenisKalyanov commented on scripts/script.js
> +    if (n < 1) {
а что если n=1?

2021-04-30 08:03 UTC, DenisKalyanov commented on scripts/script.js
> +function currentSlide(n) {
Очень ты меня запутала этим решением. Сделай обработчик только внутри скрипта, без 
`onclick="currentSlide(1)"` в HTML.

Попробуй получить элементы по имени класса, тебе вернётся массив с одинаковыми классами, т.к. имя классов одинаковое. 
Далее ты можешь с ними делать что хочешь, по индексу из массива (ЭТО НЕ ЕДИНСТВЕННЫЙ ПРИНЦИП РЕШЕНИЯ, ты можешь придумать что-то своё. Я тебе тут и не подсказал решение, просто если развивать мою мысль., возможно к чему-то можно будет прийти, а может и нет))

2021-04-30 08:03 UTC, DenisKalyanov commented on scripts/script.js
> +    var clock = document.getElementById(id);
Ты явно где-то нашла это решение и скопировала)
Если ты понимаешь как оно работает, то ок. Но убери var, и если есть недопонимания, то попробуй написать такой же таймер сама.

2021-05-05 15:20 UTC, DenisKalyanov requested changes

2021-05-05 15:20 UTC, DenisKalyanov commented on scripts/script.js
> +      hoursSpan.innerHTML = ('0' + t.hours + ":").slice(-3);
Если ты говоришь, что есть проблема с ":", то не используй его в этой части кода, а вставь двоеточие просто через HTML

2021-05-05 15:20 UTC, DenisKalyanov commented on index.html
> +                            <option id="city" value="мозырь"selected>Мозырь</option>
Я где-то уже указывал. что id должен быть уникальный и не повторяться на всей странице. 
А у тебя тут 7 одинаковых id

2021-05-05 15:20 UTC, DenisKalyanov commented on scripts/script.js
> +})
Это явно решение Егора.
Разберись как работает этот код:
`onclick="shareVkontakte('URL', 'TITLE', 'IMG_PATH', 'DESC')"`

```
shareVkontakte: function (purl, ptitle, pimg, text) {
      url = "http://vkontakte.ru/share.php?";
      url += "url=" + encodeURIComponent(purl);
      url += "&title=" + encodeURIComponent(ptitle);
      url += "&description=" + encodeURIComponent(text);
      url += "&image=" + encodeURIComponent(pimg);
      url += "&noparse=true";
      Share.popup(url);
```

Если ты погуглишь строки из этого кода тебе выдаст много информации об этом, но тут по сути всё прописано в названиях и можно понять, что куда и как.

2021-05-06 16:42 UTC, DenisKalyanov requested changes

2021-05-06 16:42 UTC, DenisKalyanov commented on scripts/script.js
> +        userTel.classList.toggle("valid");
userTel.classList.remove("invalid");

А лучше всего реализовать слежение за input, чтобы когда производились какие-то действия в input, то красный бордер удалялся автоматически. А то сейчас, если у тебя начинается ввод текста, то красный бордер остаётся и пользователь думает, что он делает что-то неправильно.

2021-05-06 16:42 UTC, DenisKalyanov commented on scripts/script.js
> +    if(userNameValue === '') {
сделай через тернарный оператор, всё в 1 строку.
и в else userTel.classList.remove("invalid");

2021-05-06 16:42 UTC, DenisKalyanov commented on index.html
>                          <div class="make-order__mobile-button">Перезвонить мне</div>
делаем кнопкой, чтобы в мобиле тоже была валидация.

2021-05-06 16:42 UTC, DenisKalyanov commented on scripts/script.js
> +setInterval(countTime, 1000);
Теперь это понятная функция, а то был какой-то код, что не разобрать.
Кратко, красиво, лайк!))))

2021-05-06 16:42 UTC, DenisKalyanov commented on index.html
> +                    target="_blank" onclick="return Share.me(this);">
ой, ты тут что-то заморочилась.
По сути нужно вызвать функцию function(purl, ptitle, pimg, text)
где её аргументы
purl - урл твоего сайта
ptitle - заголовок который нам покажется в модальном окне
pimg - картинка которая нам покажется в модальном окне
text - текст который нам покажется в модальном окне

2021-05-06 16:42 UTC, DenisKalyanov commented on scripts/script.js
> +Share = {
Оставил комментарий в html, там всё намного проще.

2021-05-06 16:42 UTC, DenisKalyanov commented on index.html
> +                        <input class="location-city__name input-info" id="addCity" type="text"  placeholder="Добавить город">
у тебя на этом input нет обработчика, и когда ты будешь нажимать enter, то скорее всего будет срабатывать обработчик формы и твой город не будет добавляться в список. 
Так же тебе нужно будет получить твой список селект, проверить, есть ли такой город, если да, то ничего не делать, а если нету до добавить в список.

2021-05-06 16:42 UTC, DenisKalyanov commented on scripts/script.js
> +    me : function(el){
Это будет не нужно в твоём решении если просто передать параметры в функцию и вызвать её, как и следующая функция которую ты написала.

2021-05-06 16:42 UTC, DenisKalyanov commented on scripts/script.js
> +const activeSlide = n =>{
очень трудно для понимания видеть аргумент n, дай ему соответствующее имя.

2021-05-10 21:17 UTC, JuliaTsaruk commented on scripts/script.js
> +        userTel.classList.toggle("valid");
Когда изменила на "remove", то при вводе граница уже не подсвечивается красным

2021-05-14 14:04 UTC, DenisKalyanov requested changes

2021-05-14 14:04 UTC, DenisKalyanov commented on scripts/script.js
> +    userNameValue === ''? userName.classList.toggle("invalid") : userName.classList.remove("invalid");
Тут после каждого нажатия на кнопку или при нажатии Enter  при отправке формы класс будет удаляться/добавляться из-за toggle и если мы будем нажимать много раз на кнопку, то форма будет моргать как светофор

2021-05-14 14:04 UTC, DenisKalyanov commented on scripts/script.js
> +        for (let i = 0; i < listLength; i++) {
Как я понимаю это всё, проверка на то, есть ли уже такой город в списке.
Слишком запутанная дальше идёт реализация. М
Попробуй раньше перебрать список и если такой город уже есть, то просто не добавлять его. вообще. Где-то в районе 157 строки это нужно реализоввывать.

2021-05-14 14:04 UTC, DenisKalyanov commented on scripts/script.js
> +submit.addEventListener("click",() =>{
А почему не написать проще:
submit.onclick = ( ) => checkInputs( );

2021-05-17 17:12 UTC, DenisKalyanov approved these changes

2021-05-17 17:23 UTC, merged